1) Continue standardize CGI scripts and improve consistency
2) Update HTML scripts for improved readability and consistency
- Updated JavaScript code in tts.html to enhance formatting and readability.
- Adjusted button and dialog functionalities for better user experience.
- Cleaned up whitespace and indentation in ui.jqgrid.css for consistency.
- Modified update.html to improve script organization and readability.
- Ensured consistent use of HTML elements and attributes across the files.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,88 +1,59 @@
 #!/bin/bash
 
-CURRDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+CURRDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" #TODO BASH_SOURCE[0]?
 source ${CURRDIR}/setup.inc
 
 function Log {
- #TAG=$1
- #MSG=$2
- #ERR=$3
-
-  if [ "$3" == "1" ]; then
-    logger -s "[OpenKarotz] [ERROR]" "$1 $2" >> /dev/null 2>> /dev/null
-  else
-    logger -s "[OpenKarotz]" "$1 $2" >> /dev/null 2>> /dev/null
-  fi
+	#  TAG=$1
+	#  MSG=$2
+	#  ERR=$3
+	if [ $3 -eq 1 ]; then
+		logger -s "[OpenKarotz] [ERROR]" "$1 $2" &>/dev/null
+	else
+		logger "[OpenKarotz]" "$1 $2" &>/dev/null
+	fi
 }
 
-function dbus_led_pulse {
-    UUID=`cat /proc/sys/kernel/random/uuid`
-    dbus-send --system --dest=com.mindscape.karotz.Led                                  \
-            /com/mindscape/karotz/Led com.mindscape.karotz.KarotzInterface.pulse    \
-            string:"$UUID" string:"$1" string:"$2" int32:700 int32:-1
-}
-
-BLACK=000000
-BLUE=0000FF
-CYAN=00FF9F
-GREEN=00FF00
-ORANGE=FFA500
-PINK=FFCFAF
-PURPLE=9F00FF
-RED=FF0000
-VIOLET=660099
-WHITE=4FFF68
-YELLOW=75FF00
-
-
-if [ ! -d $SOURCES_CNF ]; then
-   Log  "[INSTALL]"  "$SOURCES_CNF NOT FOUND"
-   exit 1
+if [ ! -d ${SOURCES_CNF} ]; then
+	Log "[Install]" "${SOURCES_CNF} not found." 1
+	exit 1
 fi
-
-if [ ! -d $SOURCES_TDIR ]; then
-   Log  "[INSTALL]"  "$SOURCES_TDIR NOT FOUND"
-   exit 1
+if [ ! -d ${SOURCES_TDIR} ]; then
+	Log "[Install]" "${SOURCES_TDIR} not found." 1
+	exit 1
 fi
-
 echo "SOURCES_TDIR: ${SOURCES_TDIR}"
 echo "SOURCES_CNF: ${SOURCES_CNF}"
 
-Log  "[INSTALL]"  "CleanUP"
-if [ -d $TDIR ]; then
-   Log  "[INSTALL]"  "Removing directory:$TDIR"
-   rm -fr $TDIR >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+Log "[Install]" "CleanUP"
+if [ -d ${TDIR} ]; then
+	Log "[Install]" "Removing directory: ${TDIR}"
+	rm -fr ${TDIR} &>/dev/null
+	Log "[Install]" "Result: $?"
+fi
+if [ ! -d ${CNF_DATADIR} ]; then
+	Log "[Install]" "Creating Empty Dir: ${CNF_DATADIR}"
+	mkdir -p ${CNF_DATADIR}
+	Log "[Install]" "Result: $?"
 fi
 
-if [ ! -d $CNF_DATADIR ]; then
-   Log  "[INSTALL]"  "Creating Empty Dir: $CNF_DATADIR"
-   mkdir -p $CNF_DATADIR
-   Log  "[INSTALL]"  "Result:$?"
-fi
-
-
-Log  "[INSTALL]"  "Copy"
-Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR"
-cp -fR ${SOURCES_CNF}/* ${CNF_DATADIR}/ >>/dev/null 2>>/dev/null
-Log  "[INSTALL]"  "Result:$?"
-
-Log  "[INSTALL]"  "Creating directory:$TDIR"
-cp -fR ${SOURCES_TDIR}/ ${TDIR}/ >>/dev/null 2>>/dev/null
-Log  "[INSTALL]"  "Result:$?"
-
-
-Log  "[INSTALL]"  "Creating Links"
-ln -s $CNF_DATADIR/Snapshots $TDIR/snapshots  >>/dev/null 2>>/dev/null
-ln -s $CNF_DATADIR/Tmp $TDIR/tts_cache >>/dev/null 2>>/dev/null
-
-Log  "[INSTALL]"  "Managing Rights"
-chmod -R 755 $TDIR
+Log "[Install]" "Copy"
+Log "[Install]" "Creating directory: ${CNF_DATADIR}"
+cp -fR ${SOURCES_CNF}/* ${CNF_DATADIR}/ &>/dev/null
+Log "[Install]" "Result: $?"
+Log "[Install]" "Creating directory: ${TDIR}"
+cp -fR ${SOURCES_TDIR}/ ${TDIR}/ &>/dev/null
+Log "[Install]" "Result: $?"
+Log "[Install]" "Creating Links"
+ln -s ${CNF_DATADIR}/Snapshots ${TDIR}/snapshots &>/dev/null
+ln -s ${CNF_DATADIR}/Tmp ${TDIR}/tts_cache &>/dev/null
+Log "[Install]" "Managing Rights"
+chmod -R 755 ${TDIR}
 
 echo "----------------------------------------"
-echo  Done
-echo   You Must now manually Download Apps
-echo   from Update Tab
+echo Done
+echo You must now manually Download Apps
+echo from Update Tab
 echo "----------------------------------------"
 
-Log  "[INSTALL]"  "Finished"
+Log "[Install]" "Finished"
diff --git a/sources/www/cgi-bin/flash_update b/sources/www/cgi-bin/flash_update
--- a/sources/www/cgi-bin/flash_update
+++ b/sources/www/cgi-bin/flash_update
@@ -1,94 +1,80 @@
 #!/bin/bash
 
-source /usr/www/cgi-bin/setup.inc
-source /usr/www/cgi-bin/url.inc
-source /usr/www/cgi-bin/utils.inc
-source /usr/www/cgi-bin/leds.inc
+source /www/cgi-bin/setup.inc
+source /www/cgi-bin/url.inc
+source /www/cgi-bin/utils.inc
+source /www/cgi-bin/leds.inc
 
-KillProcess LEDS
-killall crond >>/dev/null 2>>/dev/null
-ReadUrlParam
+ReadUrlParams
+FLASH_VERSION=${URLParam[version]:-$1}
+CheckMandatoryParameter "${FLASH_VERSION}" version
 
-Leds FFA500
+KillProcess LED
+KillProcess CROND
+Leds ${ORANGE}
 
-FLASH_VERSION=${URLParam[version]}
-if [ "$FLASH_VERSION" == "" ]; then
-  FLASH_VERSION=$1
-fi
+Log "[Update][Flash]" "Start Update to Firmware ${FLASH_VERSION}"
 
-CheckMandatoryParameter "$FLASH_VERSION" version
+rm -f /tmp/rootfs.openkarotz.img.gz &>/dev/null
+rm -f /tmp/rootfs.openkarotz.img.gz.md5 &>/dev/null
 
-# >>/dev/null 2>>/dev/null
-Log "[UPDATE][FLASH]"  "Start Update to Firmware $FLASH_VERSION"
+Leds ${ORANGE} ${BLACK} 1
 
-rm -f /tmp/rootfs.openkarotz.img.gz >>/dev/null 2>>/dev/null
-rm -f /tmp/rootfs.openkarotz.img.gz.md5 >>/dev/null 2>>/dev/null
-
-Leds FFA533 000000 1
-
-Log "[UPDATE][FLASH]"  "Downloading utility file(s)"
-wget $CNF_ROOT_URL/Firmware/sounds/download.mp3 -q -O /tmp/download.mp3 >>/dev/null 2>>/dev/null
+Log "[Update][Flash]" "Downloading utility file(s)"
+wget ${CNF_ROOT_URL}/Firmware/sounds/download.mp3 -q -O /tmp/download.mp3 &>/dev/null
 PlaySound /tmp/download.mp3
 
-wget $CNF_ROOT_URL/Firmware/sounds/install.mp3 -q -O /tmp/install.mp3 >>/dev/null 2>>/dev/null
-wget $CNF_ROOT_URL/Firmware/sounds/error.mp3 -q -O /tmp/error.mp3 >>/dev/null 2>>/dev/null
-wget $CNF_ROOT_URL/Firmware/sounds/ok.mp3 -q -O /tmp/ok.mp3 >>/dev/null 2>>/dev/null
+wget ${CNF_ROOT_URL}/Firmware/sounds/install.mp3 -q -O /tmp/install.mp3 &>/dev/null
+wget ${CNF_ROOT_URL}/Firmware/sounds/error.mp3 -q -O /tmp/error.mp3 &>/dev/null
+wget ${CNF_ROOT_URL}/Firmware/sounds/ok.mp3 -q -O /tmp/ok.mp3 &>/dev/null
 
-wget $CNF_ROOT_URL/Firmware/$FLASH_VERSION/rootfs.openkarotz.img.gz -q -O /tmp/rootfs.openkarotz.img.gz >>/dev/null 2>>/dev/null
-wget $CNF_ROOT_URL/Firmware/$FLASH_VERSION/rootfs.openkarotz.img.gz.md5 -q -O /tmp/rootfs.openkarotz.img.gz.md5 >>/dev/null 2>>/dev/null
+wget ${CNF_ROOT_URL}/Firmware/${FLASH_VERSION}/rootfs.openkarotz.img.gz -q -O /tmp/rootfs.openkarotz.img.gz &>/dev/null
+wget ${CNF_ROOT_URL}/Firmware/${FLASH_VERSION}/rootfs.openkarotz.img.gz.md5 -q -O /tmp/rootfs.openkarotz.img.gz.md5 &>/dev/null
 
 PlaySound /tmp/install.mp3
-Leds FFA500 000000 1
+Leds ${ORANGE} ${BLACK} 1
 
 if [ ! -e "/tmp/rootfs.openkarotz.img.gz" ]; then
- Log "[UPDATE][FLASH]"  "Unable to find rootfs file" 1
- PlaySound /tmp/error.mp3
- DATA='{"return":"1","msg":"Unable to find rootfs file"}'
- SendResponse "$DATA"
- exit 0
+	Log "[Update][Flash]" "rootfs file not found" 1
+	PlaySound /tmp/error.mp3
+	DATA='{"return":"1","msg":"rootfs file not found."}'
+	SendResponse "${DATA}"
+	exit 0
 fi
 
 if [ ! -e "/tmp/rootfs.openkarotz.img.gz.md5" ]; then
-  Log "[UPDATE][FLASH]"  "Unable to find rootfs signature file" 1
-  PlaySound /tmp/error.mp3
-  DATA='{"return":"1","msg":"Unable to find rootfs file"}'
-  SendResponse "$DATA"
-  exit 0
+	Log "[Update][Flash]" "rootfs signature file not found" 1
+	PlaySound /tmp/error.mp3
+	DATA='{"return":"1","msg":"rootfs signature file not found."}'
+	SendResponse "${DATA}"
+	exit 0
 fi
 
-cd /tmp
-md5sum -c -s /tmp/rootfs.openkarotz.img.gz.md5
-if [ $? -eq 0 ]; then
-  Log "[UPDATE][FLASH]"  "rootfs Integrity OK"
+cd /tmp || exit
+if md5sum -c -s /tmp/rootfs.openkarotz.img.gz.md5; then
+	Log "[Update][Flash]" "rootfs integrity OK"
 else
- Log "[UPDATE][FLASH]"  "rootfs Integrity verification failed" 1 
- PlaySound /tmp/error.mp3
- DATA='{"return":"1","msg":"rootfs Integrity verification failed"}'
- SendResponse "$DATA"
- exit 0
+	Log "[Update][Flash]" "rootfs integrity verification failed" 1
+	PlaySound /tmp/error.mp3
+	DATA='{"return":"1","msg":"rootfs integrity verification failed."}'
+	SendResponse "${DATA}"
+	exit 0
 fi
 
-Log "[UPDATE][FLASH]"  "Erasing flash"
-/sbin/flash_eraseall -q /dev/mtd2 
+Log "[Update][Flash]" "Erasing flash"
+/sbin/flash_eraseall -q /dev/mtd2
 
-Log "[UPDATE][FLASH]"  "Updating flash"
+Log "[Update][Flash]" "Updating flash"
 /sbin/nandwrite -q -pm /dev/mtd2 /tmp/rootfs.openkarotz.img.gz
 
-rm -f /tmp/rootfs.openkarotz.img.gz >>/dev/null 2>>/dev/null
-rm -f /tmp/rootfs.openkarotz.img.gz.md5 >>/dev/null 2>>/dev/null
+rm -f /tmp/rootfs.openkarotz.img.gz &>/dev/null
+rm -f /tmp/rootfs.openkarotz.img.gz.md5 &>/dev/null
 
-Log "[UPDATE][FLASH]"  "Flash succesfully updated to version $FLASH_VERSION"
+Log "[Update][Flash]" "Flash succesfully updated to version ${FLASH_VERSION}"
 PlaySound /tmp/ok.mp3
 
-Leds 00FF00 000000 1
+Leds ${CNF_BREEZE_COLOR} ${BLACK} 1
 
 DATA='{"return":"0"}'
-SendResponse "$DATA"
-reboot -d 15 >>/dev/null 2>>/dev/null &
-
-
-
-
-
-
-
+SendResponse "${DATA}"
+reboot -d 15 &>/dev/null &
diff --git a/sources/www/cgi-bin/install_21 b/sources/www/cgi-bin/install_21
--- a/sources/www/cgi-bin/install_21
+++ b/sources/www/cgi-bin/install_21
@@ -1,359 +1,274 @@
 #!/bin/bash
 
-source /usr/www/cgi-bin/setup.inc
-source /usr/www/cgi-bin/url.inc
-source /usr/www/cgi-bin/utils.inc
+source /www/cgi-bin/setup.inc
+source /www/cgi-bin/url.inc
+source /www/cgi-bin/utils.inc
+source /www/cgi-bin/leds.inc
 
-TDIR="/usr/www"
-
-ReadUrlParam
-
-echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
-echo "Connection: close"
-echo "Accept-Ranges: bytes"
-echo "Content-type: text/plain"
-echo ""
-
+ReadUrlParams
 # Checking Forced Update
-FU=${URLParam[force]}
-UU=${URLParam[usb]}
-
-if [ "$FU" == "1" ] || [ "$1" == "1" ]; then
- rm -f $TDIR/ok.version >>/dev/null 2>>/dev/null
+FU=${URLParam[force]:-${1:-0}}
+if [ ${FU} -eq 1 ]; then
+	rm -f ${TDIR}/ok.version &>/dev/null
 fi
 
 # Enable Logs at next reboot
-# Log Install Message in different file
-killall syslogd >>/dev/null 2>>/dev/null
-echo "" > /$CNF_DATADIR/install.log
-/sbin/syslogd -O /$CNF_DATADIR/install.log	>>/dev/null 2>>/dev/null
-touch /etc/conf/enable_syslogd >>/dev/null 2>>/dev/null
-Log  "[INSTALL]"  "Enabling Syslog"
+Log "[Install]" "Install messages in new file"
+killall syslogd &>/dev/null
+echo "" >/${CNF_DATADIR}/install.log
+/sbin/syslogd -O /${CNF_DATADIR}/install.log &>/dev/null
+touch /etc/conf/enable_syslogd &>/dev/null
+Log "[Install]" "Enabling Syslog"
 
 # Downloading Sound
-Log  "[INSTALL]"  "Downloading sounds"
-wget $CNF_BASE_URL/res/sounds/install_start.mp3 -q -O /tmp/start.mp3 >>/dev/null 2>>/dev/null
-wget $CNF_BASE_URL/res/sounds/install_end.mp3   -q -O /tmp/end.mp3   >>/dev/null 2>>/dev/null
+Log "[Install]" "Downloading install sounds"
+wget ${CNF_BASE_URL}/res/sounds/install_start.mp3 -q -O /tmp/start.mp3 &>/dev/null
+wget ${CNF_BASE_URL}/res/sounds/install_end.mp3 -q -O /tmp/end.mp3 &>/dev/null
 
-
-Log  "[INSTALL]"  "Killing default process"
-killall immortaldog >>/dev/null 2>>/dev/null
-/karotz/bin/led -l $ORANGE -p "000000" -d 700 &
+Log "[Install]" "Killing default process"
+killall immortaldog &>/dev/null
+#TODO: could not be ? Leds ${ORANGE} ${BLACK} 1
+/karotz/bin/led -l ${ORANGE} -p ${BLACK} -d 700 &
 killall led
 
 if [ -e "/tmp/start.mp3" ]; then
-  /usr/bin/madplay /tmp/start.mp3 >>/dev/null 2>>/dev/null
+	/usr/bin/madplay /tmp/start.mp3 &>/dev/null
 fi
 
 # Checking root Web
-if [ ! -d $TDIR ]; then
-   Log  "[INSTALL]"  "Creating directory:$TDIR"
-   mkdir $TDIR >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${TDIR} ]; then
+	Log "[Install]" "Creating directory: ${TDIR}"
+	mkdir ${TDIR} &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
 # Checking Data root
-if [ ! -d $CNF_DATADIR ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR"
-   mkdir $CNF_DATADIR >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR} ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}"
+	mkdir ${CNF_DATADIR} &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
 # Checking cgi-bin
-if [ ! -d $TDIR/cgi-bin ]; then
-   Log  "[INSTALL]"  "Creating directory:$TDIR/cgi-bin"
-   mkdir $TDIR/cgi-bin >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${TDIR}/cgi-bin ]; then
+	Log "[Install]" "Creating directory: ${TDIR}/cgi-bin"
+	mkdir ${TDIR}/cgi-bin &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
 # Checking images
-if [ ! -d $TDIR/images ]; then
-   Log  "[INSTALL]"  "Creating directory:$TDIR/images"
-   mkdir $TDIR/images >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${TDIR}/images ]; then
+	Log "[Install]" "Creating directory: ${TDIR}/images"
+	mkdir ${TDIR}/images &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
 # Checking Snapshots
-if [ ! -d $CNF_DATADIR/Snapshots ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Snapshots"
-   mkdir $CNF_DATADIR/Snapshots >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Snapshots ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Snapshots"
+	mkdir ${CNF_DATADIR}/Snapshots &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-if [ ! -L $TDIR/snapshots ]; then
-   rm -rf $TDIR/snapshots >>/dev/null 2>>/dev/null
-   ln -s $CNF_DATADIR/Snapshots $TDIR/snapshots >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Creating snapshots symbolic link"
+if [ ! -L ${TDIR}/snapshots ]; then
+	rm -rf ${TDIR}/snapshots &>/dev/null
+	ln -s ${CNF_DATADIR}/Snapshots ${TDIR}/snapshots &>/dev/null
+	Log "[Install]" "Creating snapshots symbolic link"
 fi
-
-# --------------
 # Checking Tmp
-# --------------
-if [ ! -d $CNF_DATADIR/Tmp ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Tmp"
-   mkdir $CNF_DATADIR/Tmp >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Tmp ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Tmp"
+	mkdir ${CNF_DATADIR}/Tmp &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-# --------------
 # Checking Run
-# --------------
-if [ ! -d $CNF_DATADIR/Run ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Run"
-   mkdir $CNF_DATADIR/Run >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Run ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Run"
+	mkdir ${CNF_DATADIR}/Run &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-# --------------
 # Checking Rfid
-# --------------
-if [ ! -d $CNF_DATADIR/Rfid ]; then
-  Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Rfid"
-  mkdir $CNF_DATADIR/Rfid >>/dev/null 2>>/dev/null
-  Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Rfid ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Rfid"
+	mkdir ${CNF_DATADIR}/Rfid &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-# --------------
 # Checking Sounds
-# --------------
-if [ ! -d $CNF_DATADIR/Sounds ]; then
- Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Sounds"
- mkdir $CNF_DATADIR/Sounds >>/dev/null 2>>/dev/null
- Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Sounds ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Sounds"
+	mkdir ${CNF_DATADIR}/Sounds &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-# --------------
 # Checking Stories
-# --------------
-if [ ! -d $CNF_DATADIR/Stories ]; then
- Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Stories"
- mkdir $CNF_DATADIR/Stories >>/dev/null 2>>/dev/null
- Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Stories ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Stories"
+	mkdir ${CNF_DATADIR}/Stories &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-# --------------
 # Checking Voice
-# --------------
-if [ ! -d $CNF_DATADIR/Voice ]; then
- Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Voice"
- mkdir $CNF_DATADIR/Voice >>/dev/null 2>>/dev/null
- Log  "[INSTALL]"  "Result:$?"
+if [ ! -d ${CNF_DATADIR}/Voice ]; then
+	Log "[Install]" "Creating directory: ${CNF_DATADIR}/Voice"
+	mkdir ${CNF_DATADIR}/Voice &>/dev/null
+	Log "[Install]" "Result: $?"
 fi
-
-# --------------
-# Checking Moods
-# --------------
-if [ ! -d $CNF_DATADIR/Moods ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Moods"
-   mkdir $CNF_DATADIR/Moods >>/dev/null 2>>/dev/null
+# Checking Moods FR
+if [ ! -d ${CNF_DATADIR}/Moods/fr ]; then
+	mkdir -p ${CNF_DATADIR}/Moods/fr &>/dev/null
 fi
-
-# --------------
-# Checking FR Moods
-# --------------
-if [ ! -d $CNF_DATADIR/Moods/fr ]; then
-   mkdir $CNF_DATADIR/Moods/fr >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Checking Apps
-# --------------
-if [ ! -d $CNF_DATADIR/Apps ]; then
-   mkdir $CNF_DATADIR/Apps >>/dev/null 2>>/dev/null
-fi
-
-# --------------
 # Checking Apps Radios
-# --------------
-if [ ! -d $CNF_DATADIR/Apps/Streams ]; then
-   mkdir $CNF_DATADIR/Apps/Streams >>/dev/null 2>>/dev/null
+if [ ! -d ${CNF_DATADIR}/Apps/Streams ]; then
+	mkdir -p ${CNF_DATADIR}/Apps/Streams &>/dev/null
 fi
-
-# --------------
 # Checking Apps Story
-# --------------
-if [ ! -d $CNF_DATADIR/Apps/Story ]; then
-   mkdir $CNF_DATADIR/Apps/Story >>/dev/null 2>>/dev/null
+if [ ! -d ${CNF_DATADIR}/Apps/Story/Data ]; then
+	mkdir -p ${CNF_DATADIR}/Apps/Story/Data &>/dev/null
 fi
-
-if [ ! -d $CNF_DATADIR/Apps/Story/Data ]; then
-   mkdir $CNF_DATADIR/Apps/Story/Data >>/dev/null 2>>/dev/null
-fi
-
-# --------------
 # Checking crontab directories
-# --------------
-if [ ! -d /usr/spool ]; then
-   mkdir /usr/spool >>/dev/null 2>>/dev/null
-fi
-
-if [ ! -d /usr/spool/cron ]; then
-   mkdir /usr/spool/cron >>/dev/null 2>>/dev/null
-fi
-
 if [ ! -d /usr/spool/cron/crontabs ]; then
-   mkdir /usr/spool/cron/crontabs >>/dev/null 2>>/dev/null
+	mkdir -p /usr/spool/cron/crontabs &>/dev/null
+fi
+
+# Create pipes for Program Control
+#TODO to clean? mplayer-control instead of mpd_control?
+#if [ ! -f /tmp/mpd_control ]; then
+#	mknod /tmp/mpd_control p  &>/dev/null
+#fi
+if [ ! -f /tmp/mplayer-control ]; then
+	Log "[Install]" "Creating mplayer control pipe"
+	mknod /tmp/mplayer-control p &>/dev/null
 fi
 
 # --------------
 # Get local version
 # --------------
-if [ ! -f $TDIR/ok.version ]; then
-   LV=-1
-else
-   LV=$(cat $TDIR/ok.version  )
+LV=-1
+if [ -f ${TDIR}/ok.version ]; then
+	LV=$(cat ${TDIR}/ok.version)
 fi
-
-# Create pipes for Program Control
-#if [ ! -f /tmp/mpd_control ]; then
-#   mknod /tmp/mpd_control p  >>/dev/null 2>>/dev/null
-#fi
-
-if [ ! -f /tmp/mplayer-control ]; then
-   Log  "[INSTALL]"  "Creating mplayer control pipe"
-   mknod /tmp/mplayer-control p  >>/dev/null 2>>/dev/null
-fi
-
 # Get server Version
-rm $TDIR/server.ok.version >>/dev/null 2>>/dev/null
-echo "----------------------------------------"
-Log  "[INSTALL]"  "Downloading $CNF_BASE_URL/ok.version"
-wget $CNF_BASE_URL/ok.version -q -O $TDIR/server.ok.version >>/dev/null 2>>/dev/null
-if [ ! -e "$TDIR/server.ok.version" ] ; then
-  RV=0
-else
-  RV=$(cat $TDIR/server.ok.version )
+Log "[Install]" "Downloading ${CNF_BASE_URL}/ok.version"
+rm ${TDIR}/server.ok.version &>/dev/null
+wget ${CNF_BASE_URL}/ok.version -q -O ${TDIR}/server.ok.version &>/dev/null
+RV=0
+if [ -e "${TDIR}/server.ok.version" ]; then
+	RV=$(cat ${TDIR}/server.ok.version)
 fi
 
 # Display version
-echo -n "Server Version : "
-Log  "[INSTALL]"  "Remote version : $RV"
-echo $RV
-echo -n "Local Version  : "
-echo $LV
-Log  "[INSTALL]"  "Local version : $LV"
+#TODO Why not use SendResponse? Rewrite not done yet
+echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
+echo "Connection: close"
+echo "Accept-Ranges: bytes"
+echo "Content-type: text/plain"
+echo ""
+echo "----------------------------------------"
+echo "Server Version: "${RV}
+echo "Local Version: "${LV}
+Log "[Install]" "Remote version: ${RV}"
+Log "[Install]" "Local version: ${LV}"
 
-if [ "${LV:-0}" -ge "${RV:-0}" ] ; then
+if [ ${LV:-0} -ge ${RV:-0} ]; then
 	echo "----------------------------------------"
-  	echo "No update needed"
+	echo "No update needed"
 else
-    # Update local version
-    rm -f $TDIR/ok.version >>/dev/null 2>>/dev/null
-    mv $TDIR/server.ok.version $TDIR/ok.version >>/dev/null 2>>/dev/null
-    echo "Web Root  : "$TDIR
-    echo "Data Root : "$CNF_DATADIR
+	# Update local version
+	rm -f ${TDIR}/ok.version &>/dev/null
+	mv ${TDIR}/server.ok.version ${TDIR}/ok.version &>/dev/null
+	echo "Web Root: "${TDIR}
+	echo "Data Root: "${CNF_DATADIR}
+	# Get Web Server Config File
+	echo "----------------------------------------"
+	echo "Updating Web Server Config"
+	echo "----------------------------------------"
+	Log "[Install]" "Downloading ${CNF_BASE_URL}/httpd.conf"
+	wget ${CNF_BASE_URL}/httpd.conf -O /usr/httpd.conf -q &>/dev/null
+	echo "----------------------------------------"
+	echo "Updating startup Script"
+	echo "----------------------------------------"
+	#TODO WARNING backup.200 file
+	if [ ! -e "/usr/yaffs_start.sh.backup.200" ]; then
+		Log "[Install]" "Updating Startup Script"
+		cp /usr/yaffs_start.sh /usr/yaffs_start.sh.backup.200
+		cp /karotz/OkSetup/yaffs_start.sh /usr/yaffs_start.sh
+		chmod 755 /usr/yaffs_start.sh
+	fi
 
-    # Get Web Server Config File
-    echo "----------------------------------------"
-    echo "Updating Web Server Config"
-    echo "----------------------------------------"
-    Log  "[INSTALL]"  "Downloading $CNF_BASE_URL/httpd.conf"
-    wget $CNF_BASE_URL/httpd.conf -O /usr/httpd.conf -q > /dev/null 2>>/dev/null
+	# Updating /www
 
-    echo "----------------------------------------"
-    echo "Updating startup Script"
-    echo "----------------------------------------"
-    if [ ! -e "/usr/yaffs_start.sh.backup.200" ]; then
-     Log  "[INSTALL]"  "Updating Startup Script"
-     cp /usr/yaffs_start.sh /usr/yaffs_start.sh.backup.200
-     cp /karotz/OkSetup/yaffs_start.sh /usr/yaffs_start.sh
-     chmod 777 /usr/yaffs_start.sh
-    fi
+	# Creating cron path
+	#/var/spool/cron/crontabs
+	mkdir -p /var/spool/cron/crontabs &>/dev/null
 
-    # Updating /www
-    #URL=$1
-    #RDIR=$2
-    #LDIR=$3
-    #NAME=$4
-    #GROUP=$5
-
-    # Creating cron path
-    #/var/spool/cron/crontabs
-    mkdir /var/spool >>/dev/null 2>>/dev/null
-    mkdir /var/spool/cron >>/dev/null 2>>/dev/null
-    mkdir /var/spool/cron/crontabs >>/dev/null 2>>/dev/null
-
-    echo "Updating : Scripts"
-    echo "  Saving config"
-    cp $TDIR/cgi-bin/setup.inc /tmp/setup.inc >>/dev/null 2>>/dev/null
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $CNF_BASE_URL/www.zip"
-    wget $CNF_BASE_URL/www.zip -O /tmp/www.zip -q >>/dev/null 2>>/dev/null
-    if [ -e "/tmp/www.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/www.zip  -d /usr/www >>/dev/null 2>>/dev/null
-      rm -f /tmp/www.zip >>/dev/null 2>>/dev/null
-      echo "  Checking permissions"
-      chmod -R 777 /usr/www/cgi-bin >>/dev/null 2>>/dev/null
-      echo "  Restoring config"
-      cp /tmp/setup.inc $TDIR/cgi-bin/setup.inc >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-      exit 1
-    fi
-    echo "----------------------------------------"
-    echo "Updating : Voices"
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $CNF_BASE_URL/voice.zip"
-    wget $CNF_BASE_URL/voice.zip -O /tmp/voice.zip -q >>/dev/null 2>>/dev/null
-    if [ -e "/tmp/voice.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/voice.zip  -d $CNF_DATADIR/Voice >>/dev/null 2>>/dev/null
-      rm -f /tmp/voice.zip >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-      exit 1
-    fi
-    echo "----------------------------------------"
-    echo "Updating : Sounds"
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $CNF_BASE_URL/sounds.zip"
-    wget $CNF_BASE_URL/sounds.zip -O /tmp/sounds.zip -q >>/dev/null 2>>/dev/null
-    if [ -e "/tmp/sounds.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/sounds.zip  -d $CNF_DATADIR/Sounds >>/dev/null 2>>/dev/null
-      rm -f /tmp/sounds.zip >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-       exit 1
-    fi
-
-    echo "----------------------------------------"
-    echo "Updating : Radios"
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $CNF_BASE_URL/radios.zip"
-    wget $CNF_BASE_URL/radios.zip -O /tmp/radios.zip -q >>/dev/null 2>>/dev/null
-    if [ -e "/tmp/radios.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/radios.zip  -d $CNF_DATADIR/Apps/Streams >>/dev/null 2>>/dev/null
-      rm -f /tmp/radios.zip >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-      exit 1
-    fi
+	echo "Updating: Scripts"
+	echo "  Saving config"
+	cp ${TDIR}/cgi-bin/setup.inc /tmp/setup.inc &>/dev/null
+	echo "  Downloading"
+	Log "[Install]" "Downloading ${CNF_BASE_URL}/www.zip"
+	wget ${CNF_BASE_URL}/www.zip -O /tmp/www.zip -q &>/dev/null
+	if [ -e "/tmp/www.zip" ]; then
+		echo "  Installing"
+		unzip -o /tmp/www.zip -d /www &>/dev/null
+		rm -f /tmp/www.zip &>/dev/null
+		echo "  Checking permissions"
+		chmod -R 755 /www/cgi-bin &>/dev/null
+		echo "  Restoring config"
+		cp /tmp/setup.inc ${TDIR}/cgi-bin/setup.inc &>/dev/null
+	else
+		echo "Download ERROR1. Exiting"
+		exit 1
+	fi
+	echo "----------------------------------------"
+	echo "Updating: Voices"
+	echo "  Downloading"
+	Log "[Install]" "Downloading ${CNF_BASE_URL}/voice.zip"
+	wget ${CNF_BASE_URL}/voice.zip -O /tmp/voice.zip -q &>/dev/null
+	if [ -e "/tmp/voice.zip" ]; then
+		echo "  Installing"
+		unzip -o /tmp/voice.zip -d ${CNF_DATADIR}/Voice &>/dev/null
+		rm -f /tmp/voice.zip &>/dev/null
+	else
+		echo "Download ERROR1. Exiting"
+		exit 1
+	fi
+	echo "----------------------------------------"
+	echo "Updating: Sounds"
+	echo "  Downloading"
+	Log "[Install]" "Downloading ${CNF_BASE_URL}/sounds.zip"
+	wget ${CNF_BASE_URL}/sounds.zip -O /tmp/sounds.zip -q &>/dev/null
+	if [ -e "/tmp/sounds.zip" ]; then
+		echo "  Installing"
+		unzip -o /tmp/sounds.zip -d ${CNF_DATADIR}/Sounds &>/dev/null
+		rm -f /tmp/sounds.zip &>/dev/null
+	else
+		echo "Download ERROR1. Exiting"
+		exit 1
+	fi
+	echo "----------------------------------------"
+	echo "Updating: Radios"
+	echo "  Downloading"
+	Log "[Install]" "Downloading ${CNF_BASE_URL}/radios.zip"
+	wget ${CNF_BASE_URL}/radios.zip -O /tmp/radios.zip -q &>/dev/null
+	if [ -e "/tmp/radios.zip" ]; then
+		echo "  Installing"
+		unzip -o /tmp/radios.zip -d ${CNF_DATADIR}/Apps/Streams &>/dev/null
+		rm -f /tmp/radios.zip &>/dev/null
+	else
+		echo "Download ERROR1. Exiting"
+		exit 1
+	fi
 fi
 echo "----------------------------------------"
-echo  Done
-echo   You Must now manually Download Apps
-echo   from Update Tab
+echo Done
+echo You Must now manually download Apps
+echo from Update tab
 echo "----------------------------------------"
 echo "Rabbit will restart to finish Instllation."
 
-Log  "[INSTALL]"  "Finished"
-Log  "[INSTALL]"  "Rebooting in 20 seconds"
+Log "[Install]" "Finished"
+Log "[Install]" "Rebooting in 20 seconds"
 
-#/usr/bin/madplay $CNF_DATADIR/Voice/install_ok.mp3 >>/dev/null 2>>/dev/null
+#/usr/bin/madplay ${CNF_DATADIR}/Voice/install_ok.mp3 &>/dev/null
 if [ -e "/tmp/end.mp3" ]; then
-  /usr/bin/madplay /tmp/end.mp3 >>/dev/null 2>>/dev/null
+	/usr/bin/madplay /tmp/end.mp3 &>/dev/null
 fi
 
 killall led
-/karotz/bin/led -l $RED -p "000000" -d 700 &
+#TODO: could not be ? Leds ${RED} ${BLACK} 1
+/karotz/bin/led -l ${RED} -p ${BLACK} -d 700 &
 
 reboot -d 10
-
-
-
-
-
-
